// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdapwdgtyukatrtyhpfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkYXB3ZGd0eXVrYXRydHlocGZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjk3OTEsImV4cCI6MjA2Mzg0NTc5MX0.nC1mO--b4uzbHW1HIPSTbOex3eyEqHAnM-z12JB-JYs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);